spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lailaidoutu?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    druid:
      whiteList: 127.0.0.1
      blackList: 192.168.1.254
      username: luowen
      password: luowen
      isResetData: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect :  org.hibernate.dialect.MySQL5Dialect
    #懒加载配置
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
logging:
  level:
    org:
      springframework:
        web: info

    com:
       lailaidoutu: info
  file: lailaidoutu.log






